free_thresh: 0.90
negate: 0
origin: [-5.000000, -5.000000, 0.0]
resolution: 0.050000
mode: trinary
occupied_thresh: 0.95
image: /home/user1/ros2_workspace/src/ergocub_navigation/config/maps/docker_sim_v1_map.pgm
